Update container image name for e2e tests
mongodb/mongodb-kubernetes-operator pull request #1081
Opened 2022-08-16 15:51 UTC by jamesbroadhead

2022-08-16 15:52 UTC, irajdeep approved these changes

2022-08-17 06:05 UTC, slaskawi requested changes
@jamesbroadhead Could you please exclude the `helm-charts` updates from this Pull Request?

Apart from that - LGTM!

2022-08-22 05:24 UTC, slaskawi approved these changes

2022-08-22 05:24 UTC, merged

2022-08-22 05:24 UTC, slaskawi commented
Integrated, thanks @jamesbroadhead !