feat: kustomize-able cluster-wide operator deploy
mongodb/mongodb-kubernetes-operator pull request #858
Opened 2022-01-18 00:36 UTC by bugslifesolutions

- Fix #1 ClusterRoleBinding , placeholder namespace
- separation of singleNamespace vs clusterwide RBAC
- cluster-wide manager patch
- Renamed files to better reflect responsibility

### All Submissions:

* [ x ] Have you opened an Issue before filing this PR?
* [ x ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ x ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2022-01-24 11:35 UTC, rodrigovalin requested changes
Hi @bugslifesolutions 

It took me a while to understand what you are trying to do here, but finally I got it. Next time, please add a narrative/summary of your changes and goals with the patch.

From what I can see, you are creating `single-namespace` and `clusterwide` overlays on top of the Operator deployment, by moving `deploy/clusterwide` definitions into `kustomize` directory.

Additional to the narrative to why this is needed (and how you are will be doing it), it will be good if you could add 2 examples of **how to install the operator in both single-namespace and clusterwide modes**. With a good explanation of **why** and **how** it will be much easier for us to asses the value of this contribution and be able to merge it.

We always welcome contributions! Please see my comments below for the changes we need before proceeding with this patch.

2022-01-24 11:35 UTC, rodrigovalin commented on config/operator/clusterwide/kustomization.yaml
> +  - ./operator_Deployment_patch.yaml
please use `snake_case_for_filenames.yaml`

And don't forget to add a new line at the end of the file (your editor should do this for you if your configure it properly)

2022-01-24 12:49 UTC, bugslifesolutions commented
Thank you for your patience and coaching.  I'll make those changes and
include some kustimize examples.


On Mon, Jan 24, 2022, 6:35 AM 'Rodrigo Valin' via business <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @bugslifesolutions <https://github.com/bugslifesolutions>
>
> It took me a while to understand what you are trying to do here, but
> finally I got it. Next time, please add a narrative/summary of your changes
> and goals with the patch.
>
> From what I can see, you are creating single-namespace and clusterwide
> overlays on top of the Operator deployment, by moving deploy/clusterwide
> definitions into kustomize directory.
>
> Additional to the narrative to why this is needed (and how you are will be
> doing it), it will be good if you could add 2 examples of *how to install
> the operator in both single-namespace and clusterwide modes*. With a good
> explanation of *why* and *how* it will be much easier for us to asses the
> value of this contribution and be able to merge it.
>
> We always welcome contributions! Please see my comments below for the
> changes we need before proceeding with this patch.
> ------------------------------
>
> In config/operator/base/kustomization.yaml
> <https://github.com/mongodb/mongodb-kubernetes-operator/pull/858#discussion_r790627229>
> :
>
> > @@ -1,5 +1,5 @@
>  resources:
> -- manager.yaml
> +- operator_Deployment.yaml
>
> You should not rename this file, this is the standard for us (even if not
> a perfect name)
> ------------------------------
>
> In config/operator/clusterwide/kustomization.yaml
> <https://github.com/mongodb/mongodb-kubernetes-operator/pull/858#discussion_r790629256>
> :
>
> > @@ -0,0 +1,5 @@
> +bases:
> +  - ../base
> +
> +patches:
> +  - ./operator_Deployment_patch.yaml
>
> please use snake_case_for_filenames.yaml
>
> And don't forget to add a new line at the end of the file (your editor
> should do this for you if your configure it properly)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mongodb/mongodb-kubernetes-operator/pull/858#pullrequestreview-860787542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADUMDE5IDXP7DF7LHKNO4B3UXU2QXANCNFSM5MF3S6VQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-14 13:26 UTC, rodrigovalin commented
@bugslifesolutions 

Please make sure you follow the mandatory requirements under the `All Submissions` section. The most important of them (at this stage) is that there needs to be an Issue created, discussed and agreed on a solution.

The problem you are trying to solve has not been discussed and the description of this change is very poor. It is not clear enough for us why you are making this change, what problem are you trying to solve and we have not agreed that this particular solution is the one we want for this particular problem.

At the same time, there's a failing test that you *have* to fix before we review this change.

2022-10-28 13:10 UTC, irajdeep commented
Closing this PR, feel free to reopen if you would to continue working on this.

2022-10-28 13:10 UTC, closed without merging